# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        tags: 'aws_terraform'
    - task: PowerShell@2
      name: Terraform
      inputs:
        targetType: 'inline'
        script: |
          terraform init -input=false
          terraform apply -input=false -auto-approve
          $repo_url = terraform output
          echo "##vso[task.setvariable variable=repo_url]$repo_url"
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host $env:repo_url
