# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          terraform init -input=false
          terraform apply -input=false -auto-approve
          json_url=$(terraform output -json test_terraform_output_url)
          echo "##vso[task.setvariable variable=json_url]$json_url"
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        tags: 'aws_terraform'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws ecr get-login-password --region $(TF_VAR_AWS_DEFAULT_REGION) | docker login --username AWS --password-stdin $(json_url).Split("/")[0]
          docker push $(json_url):latest